### ISSUE TITLE
Why still calculate loss when conducting evaluation? and IndexError reported also

### ISSUE THREAD

**Issue by baolongliu** [amazon-research/semimtr-text-recognition#5] opened 2022-10-09 13:14 UTC
[2022-10-09 21:10:13,443 main.py:283 INFO consistency-regularization] Construct dataset.
[2022-10-09 21:10:13,478 main.py:129 INFO consistency-regularization] 4485536 training items found.
[2022-10-09 21:10:13,478 main.py:131 INFO consistency-regularization] 62944 valid items found.
[2022-10-09 21:10:13,478 main.py:133 INFO consistency-regularization] 147209 test items found.
[2022-10-09 21:10:13,478 main.py:289 INFO consistency-regularization] Construct model.
[2022-10-09 21:10:13,789 model_vision.py:38 INFO consistency-regularization] Read vision model from workdir/semimtr_vision_model_real_l_and_u.pth.
[2022-10-09 21:10:33,487 model_language.py:38 INFO consistency-regularization] Read language model from workdir/abinet_language_model.pth.
[2022-10-09 21:10:33,537 main.py:292 INFO consistency-regularization] Construct learner.
[2022-10-09 21:10:33,597 main.py:301 INFO consistency-regularization] Start testing
Traceback (most recent call last):------------------| 0.00% [0/2 00:00<?]
  File "main.py", line 306, in <module>
    main()
  File "main.py", line 302, in main
    test_on_each_ds(learner)
  File "/media/disk4/flbl/cdsme/semimtr/semimtr/utils/test.py", line 19, in test_on_each_ds
    last_metrics = learner.validate(dl=dl)
  File "/home/lbl/miniconda3/envs/semimtr/lib/python3.7/site-packages/fastai/basic_train.py", line 391, in validate
    val_metrics = validate(self.model, dl, self.loss_func, cb_handler)
  File "/home/lbl/miniconda3/envs/semimtr/lib/python3.7/site-packages/fastai/basic_train.py", line 59, in validate
    val_loss = loss_batch(model, xb, yb, loss_func, cb_handler=cb_handler)
  File "/home/lbl/miniconda3/envs/semimtr/lib/python3.7/site-packages/fastai/basic_train.py", line 30, in loss_batch
    loss = loss_func(out, *yb)
  File "/home/lbl/miniconda3/envs/semimtr/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/media/disk4/flbl/cdsme/semimtr/semimtr/losses/consistency_regularization_loss.py", line 73, in forward
    pt_lengths_teacher, *args[2:], mask=threshold_mask)
  File "/home/lbl/miniconda3/envs/semimtr/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/media/disk4/flbl/cdsme/semimtr/semimtr/losses/losses.py", line 62, in forward
    gt_labels, gt_lengths = gt_dict['label'], gt_dict['length']
IndexError: too many indices for tensor of dimension 3

**Comment by baolongliu** [comment] 2022-10-14 09:59
Why does a dict type variable turn to be a Tensor? @aaberdam I used the lmdb data the author provided.

 https://github.com/amazon-research/semimtr-text-recognition/blob/9263639dda4a8323b29e7c52663046a5d190ba2a/semimtr/losses/losses.py#L61
![image](https://user-images.githubusercontent.com/92018562/195819373-f36b69af-d96a-41f7-849e-8dc3271c58ee.png)

**Comment by dikubab** [comment] 2022-10-15 08:27
I am facing the same issue. The error occurs in finetuning stage only.  
![Screen Shot 2022-10-15 at 4 25 14 PM](https://user-images.githubusercontent.com/60455687/195977176-6e5bdce3-7f52-47f7-a16e-cd421502b1ad.png)

**Comment by aaberdam** [comment] 2022-10-16 11:53
Hi, 

Thank you for raising this issue.
As you said, you don't have to calculate the loss on the test set; however, it does indicate what is the distribution shift with the train set, and therefore, we calculate it.
I will soon provide a fix for this and update here in the issue.

Thank you

**Comment by aaberdam** [comment] 2022-10-16 13:45
Please take a look on this commit: https://github.com/amazon-research/semimtr-text-recognition/commit/73956fb35b870cf73d02b070b389572ee471e1a4
I believe it solves the issue.
Please let me know otherwise.

Thank you again for raising this issue,
Aviad

**Comment by dikubab** [comment] 2022-10-16 14:24
@aaberdam Thank you very much for the follow-up and updates. For me the problem is solved after the update of the commit https://github.com/amazon-research/semimtr-text-recognition/commit/73956fb35b870cf73d02b070b389572ee471e1a4. I think we can close the issue.

**Closed** 2022-10-16 14:26 UTC
